-- SISTEMA DE VIÁTICOS - ESTRUCTURA DE TABLAS
-- Ejecutar: psql -U postgres -d siag_dev_local -f tabla_actividades.sql

-- 1. Tabla para almacenar las actividades
CREATE TABLE IF NOT EXISTS public.actividades
(
    id_actividad integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_usuario integer NOT NULL,
    fecha date NOT NULL,
    hora time NOT NULL,
    tipo_lugar text COLLATE pg_catalog."default" NOT NULL CHECK (tipo_lugar IN ('pais', 'estado', 'municipio')),
    lugar text COLLATE pg_catalog."default" NOT NULL,
    id_municipio integer,
    direccion text COLLATE pg_catalog."default" NOT NULL,
    motivo text COLLATE pg_catalog."default" NOT NULL,
    tipo text COLLATE pg_catalog."default" NOT NULL CHECK (tipo IN ('administrativo', 'evento')),
    fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP,
    esta_borrado boolean NOT NULL DEFAULT false,
    CONSTRAINT actividades_pkey PRIMARY KEY (id_actividad),
    CONSTRAINT actividades_id_usuario_fkey FOREIGN KEY (id_usuario)
        REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT actividades_id_municipio_fkey FOREIGN KEY (id_municipio)
        REFERENCES public.municipios (id_municipio) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 2. Tabla para firmas (catálogo de firmas disponibles)
CREATE TABLE IF NOT EXISTS public.firmas
(
    id_firma integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_firma text COLLATE pg_catalog."default" NOT NULL,
    cargo_firma text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    esta_borrado boolean NOT NULL DEFAULT false,
    CONSTRAINT firmas_pkey PRIMARY KEY (id_firma)
);

-- 3. Tabla para asignar firmas por área (qué firma corresponde a cada área)
CREATE TABLE IF NOT EXISTS public.firmas_por_area
(
    id_firma_area integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_area integer NOT NULL,
    id_firma integer NOT NULL,
    esta_borrado boolean NOT NULL DEFAULT false,
    CONSTRAINT firmas_por_area_pkey PRIMARY KEY (id_firma_area),
    CONSTRAINT firmas_por_area_id_area_fkey FOREIGN KEY (id_area)
        REFERENCES public.areas (id_area) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT firmas_por_area_id_firma_fkey FOREIGN KEY (id_firma)
        REFERENCES public.firmas (id_firma) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 4. Tabla para memorandum y comisión
CREATE TABLE IF NOT EXISTS public.memorandum_comision
(
    id_memorandum_comision integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_actividad integer NOT NULL,
    id_empleado integer NOT NULL,
    periodo_inicio date NOT NULL,
    periodo_fin date NOT NULL,
    tipo_transporte text COLLATE pg_catalog."default" NOT NULL CHECK (tipo_transporte IN ('publico', 'oficial', 'aereo')),
    id_firma integer NOT NULL,
    fecha_creacion timestamp DEFAULT CURRENT_TIMESTAMP,
    esta_borrado boolean NOT NULL DEFAULT false,
    CONSTRAINT memorandum_comision_pkey PRIMARY KEY (id_memorandum_comision),
    CONSTRAINT memorandum_comision_id_actividad_fkey FOREIGN KEY (id_actividad)
        REFERENCES public.actividades (id_actividad) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT memorandum_comision_id_empleado_fkey FOREIGN KEY (id_empleado)
        REFERENCES public.empleados (id_empleado) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT memorandum_comision_id_firma_fkey FOREIGN KEY (id_firma)
        REFERENCES public.firmas (id_firma) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.actividades OWNER to postgres;
ALTER TABLE IF EXISTS public.firmas OWNER to postgres;
ALTER TABLE IF EXISTS public.firmas_por_area OWNER to postgres;
ALTER TABLE IF EXISTS public.memorandum_comision OWNER to postgres;

COMMENT ON COLUMN public.actividades.id_actividad IS 'ID único de la actividad';
COMMENT ON COLUMN public.actividades.id_usuario IS 'Usuario que registra la actividad';
COMMENT ON COLUMN public.actividades.fecha IS 'Fecha de la actividad';
COMMENT ON COLUMN public.actividades.hora IS 'Hora de la actividad';
COMMENT ON COLUMN public.actividades.tipo_lugar IS 'Tipo de lugar: pais, estado, municipio';
COMMENT ON COLUMN public.actividades.lugar IS 'Nombre del lugar (país, estado o ID municipio)';
COMMENT ON COLUMN public.actividades.id_municipio IS 'ID del municipio (solo si tipo_lugar = municipio)';
COMMENT ON COLUMN public.actividades.direccion IS 'Dirección específica del lugar';
COMMENT ON COLUMN public.actividades.motivo IS 'Motivo de la actividad';
COMMENT ON COLUMN public.actividades.tipo IS 'Tipo: administrativo o evento';
COMMENT ON COLUMN public.actividades.fecha_creacion IS 'Fecha de registro';
COMMENT ON COLUMN public.actividades.esta_borrado IS 'Borrado lógico';

-- Comentarios para tabla firmas
COMMENT ON COLUMN public.firmas.id_firma IS 'ID único de la firma';
COMMENT ON COLUMN public.firmas.nombre_firma IS 'Nombre de quien firma';
COMMENT ON COLUMN public.firmas.cargo_firma IS 'Cargo de quien firma';
COMMENT ON COLUMN public.firmas.descripcion IS 'Descripción adicional';

-- Comentarios para tabla firmas_por_area
COMMENT ON COLUMN public.firmas_por_area.id_firma_area IS 'ID único';
COMMENT ON COLUMN public.firmas_por_area.id_area IS 'Área que usa esta firma';
COMMENT ON COLUMN public.firmas_por_area.id_firma IS 'Firma asignada al área';

-- Comentarios para tabla memorandum_comision
COMMENT ON COLUMN public.memorandum_comision.id_memorandum_comision IS 'ID único';
COMMENT ON COLUMN public.memorandum_comision.id_actividad IS 'Actividad relacionada';
COMMENT ON COLUMN public.memorandum_comision.id_empleado IS 'Empleado comisionado';
COMMENT ON COLUMN public.memorandum_comision.periodo_inicio IS 'Fecha inicio del período';
COMMENT ON COLUMN public.memorandum_comision.periodo_fin IS 'Fecha fin del período';
COMMENT ON COLUMN public.memorandum_comision.tipo_transporte IS 'Tipo: publico, oficial, aereo';
COMMENT ON COLUMN public.memorandum_comision.id_firma IS 'Firma del jefe de área';