-- Tabla de bancos de México
CREATE TABLE IF NOT EXISTS public.bancos
(
    id_banco integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    codigo_banco text COLLATE pg_catalog."default" NOT NULL,
    nombre_banco text COLLATE pg_catalog."default" NOT NULL,
    esta_borrado boolean NOT NULL DEFAULT false,
    CONSTRAINT bancos_pkey PRIMARY KEY (id_banco)
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bancos
    OWNER to postgres;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.bancos TO apps;
GRANT ALL ON TABLE public.bancos TO postgres;
GRANT SELECT ON TABLE public.bancos TO readers;

COMMENT ON COLUMN public.bancos.id_banco IS 'ID del banco';
COMMENT ON COLUMN public.bancos.codigo_banco IS 'Código del banco (3 dígitos)';
COMMENT ON COLUMN public.bancos.nombre_banco IS 'Nombre del banco';
COMMENT ON COLUMN public.bancos.esta_borrado IS 'Borrado lógico';

-- Tabla de cuentas bancarias de empleados
CREATE TABLE IF NOT EXISTS public.cuentas_bancarias_empleados
(
    id_cuenta_bancaria integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_empleado integer NOT NULL,
    id_banco integer NOT NULL,
    numero_cuenta text COLLATE pg_catalog."default" NOT NULL,
    clabe text COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    esta_borrado boolean NOT NULL DEFAULT false,
    CONSTRAINT cuentas_bancarias_empleados_pkey PRIMARY KEY (id_cuenta_bancaria),
    CONSTRAINT fk_cuenta_empleado FOREIGN KEY (id_empleado)
        REFERENCES public.empleados (id_empleado) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_cuenta_banco FOREIGN KEY (id_banco)
        REFERENCES public.bancos (id_banco) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.cuentas_bancarias_empleados
    OWNER to postgres;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.cuentas_bancarias_empleados TO apps;
GRANT ALL ON TABLE public.cuentas_bancarias_empleados TO postgres;
GRANT SELECT ON TABLE public.cuentas_bancarias_empleados TO readers;

COMMENT ON COLUMN public.cuentas_bancarias_empleados.id_cuenta_bancaria IS 'ID de la cuenta bancaria';
COMMENT ON COLUMN public.cuentas_bancarias_empleados.id_empleado IS 'ID del empleado';
COMMENT ON COLUMN public.cuentas_bancarias_empleados.id_banco IS 'ID del banco';
COMMENT ON COLUMN public.cuentas_bancarias_empleados.numero_cuenta IS 'Número de cuenta bancaria';
COMMENT ON COLUMN public.cuentas_bancarias_empleados.clabe IS 'CLABE interbancaria';
COMMENT ON COLUMN public.cuentas_bancarias_empleados.fecha_creacion IS 'Fecha de creación del registro';
COMMENT ON COLUMN public.cuentas_bancarias_empleados.esta_borrado IS 'Borrado lógico';

-- Insertar algunos bancos principales de México
INSERT INTO public.bancos (codigo_banco, nombre_banco) VALUES
('002', 'BANAMEX'),
('012', 'BBVA MÉXICO'),
('014', 'SANTANDER'),
('019', 'BANJERCITO'),
('021', 'HSBC'),
('030', 'BAJÍO'),
('032', 'IXE'),
('036', 'INBURSA'),
('037', 'INTERACCIONES'),
('042', 'MIFEL'),
('044', 'SCOTIABANK'),
('058', 'BANREGIO'),
('059', 'INVEX'),
('060', 'BANSI'),
('062', 'AFIRME'),
('072', 'BANORTE'),
('103', 'AMERICAN EXPRESS'),
('106', 'BANK OF AMERICA'),
('108', 'MUFG'),
('110', 'JP MORGAN'),
('112', 'BMONEX'),
('113', 'VE POR MAS'),
('116', 'AZTECA'),
('124', 'DEUTSCHE'),
('126', 'CREDIT SUISSE'),
('127', 'AZTECA'),
('128', 'AUTOFIN'),
('129', 'BARCLAYS'),
('130', 'COMPARTAMOS'),
('131', 'BANCO FAMSA'),
('132', 'BMULTIVA'),
('133', 'ACTINVER'),
('134', 'WAL-MART'),
('135', 'NAFIN'),
('136', 'INTERBANCO'),
('137', 'BANCOPPEL'),
('138', 'ABC CAPITAL'),
('139', 'UBS BANK'),
('140', 'CONSUBANCO'),
('141', 'VOLKSWAGEN'),
('143', 'CIBANCO'),
('145', 'BBASE'),
('166', 'BANSEFI'),
('168', 'HIPOTECARIA FEDERAL'),
('600', 'MONEXCB'),
('601', 'GBM'),
('602', 'MASARI'),
('605', 'VALUE'),
('606', 'ESTRUCTURADORES'),
('607', 'TIBER'),
('608', 'VECTOR'),
('610', 'B&B'),
('614', 'ACCIVAL'),
('615', 'MERRILL LYNCH'),
('616', 'FINAMEX'),
('617', 'VALMEX'),
('618', 'UNICA'),
('619', 'MAPFRE'),
('620', 'PROFUTURO'),
('621', 'CB ACTINVER'),
('622', 'OACTIN'),
('623', 'SKANDIA'),
('626', 'CBDEUTSCHE'),
('627', 'ZURICH'),
('628', 'ZURICHVI'),
('629', 'SU CASITA'),
('630', 'CB INTERCAM'),
('631', 'CI BOLSA'),
('632', 'BULLTICK CB'),
('633', 'STERLING'),
('634', 'FINCOMUN'),
('636', 'HDI SEGUROS'),
('637', 'ORDER'),
('638', 'AKALA'),
('640', 'CB JPMORGAN'),
('642', 'REFORMA'),
('646', 'STP'),
('647', 'TELECOMM'),
('648', 'EVERCORE'),
('649', 'SKANDIA'),
('651', 'SEGMTY'),
('652', 'ASEA'),
('653', 'KUSPIT'),
('655', 'SOFIEXPRESS'),
('656', 'UNAGRA'),
('659', 'OPCIONES EMPRESARIALES DEL NOROESTE'),
('670', 'LIBERTAD'),
('901', 'CLS'),
('902', 'INDEVAL'),
('999', 'N/A')
ON CONFLICT DO NOTHING;