-- Crear tabla para firmas adicionales por empleado
CREATE TABLE IF NOT EXISTS public.firmas_adicionales_empleado
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_empleado integer NOT NULL,
    id_firma integer NOT NULL,
    fecha_asignacion timestamp DEFAULT CURRENT_TIMESTAMP,
    esta_borrado boolean NOT NULL DEFAULT false,
    CONSTRAINT firmas_adicionales_empleado_pkey PRIMARY KEY (id),
    CONSTRAINT firmas_adicionales_empleado_id_empleado_fkey FOREIGN KEY (id_empleado)
        REFERENCES public.empleados (id_empleado) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT firmas_adicionales_empleado_id_firma_fkey FOREIGN KEY (id_firma)
        REFERENCES public.firmas (id_firma) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.firmas_adicionales_empleado OWNER to postgres;

COMMENT ON COLUMN public.firmas_adicionales_empleado.id IS 'ID único';
COMMENT ON COLUMN public.firmas_adicionales_empleado.id_empleado IS 'Empleado al que se asigna la firma adicional';
COMMENT ON COLUMN public.firmas_adicionales_empleado.id_firma IS 'Firma adicional asignada';
COMMENT ON COLUMN public.firmas_adicionales_empleado.fecha_asignacion IS 'Fecha de asignación';
COMMENT ON COLUMN public.firmas_adicionales_empleado.esta_borrado IS 'Borrado lógico';