const pool = require('../config/database');

async function recreateSchema() {
    const client = await pool.connect();    
    try {
        await client.query('BEGIN');

        console.log('Iniciando recreación de tabla memorandum_comision...');

        // 1. Eliminar tabla existente
        console.log('Eliminando tabla existente...');
        await client.query('DROP TABLE IF EXISTS public.memorandum_comision CASCADE');

        // 2. Crear nueva tabla con el orden deseado
        console.log('Creando tabla con nueva estructura...');
        await client.query(`
      CREATE TABLE public.memorandum_comision
      (
          id_memorandum_comision integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
          folio character varying(50),
          id_actividad integer NOT NULL,
          id_empleado integer NOT NULL,
          periodo_inicio date NOT NULL,
          periodo_fin date NOT NULL,
          tipo_transporte text COLLATE pg_catalog."default" NOT NULL,
          id_firma integer NOT NULL,
          fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
          esta_borrado boolean NOT NULL DEFAULT false,
          observaciones text COLLATE pg_catalog."default",
          id_vehiculo integer,
          CONSTRAINT memorandum_comision_pkey PRIMARY KEY (id_memorandum_comision),
          CONSTRAINT memorandum_comision_id_actividad_fkey FOREIGN KEY (id_actividad)
              REFERENCES public.actividades (id_actividad) MATCH SIMPLE
              ON UPDATE NO ACTION
              ON DELETE NO ACTION,
          CONSTRAINT memorandum_comision_id_empleado_fkey FOREIGN KEY (id_empleado)
              REFERENCES public.empleados (id_empleado) MATCH SIMPLE
              ON UPDATE NO ACTION
              ON DELETE NO ACTION,
          CONSTRAINT memorandum_comision_id_firma_fkey FOREIGN KEY (id_firma)
              REFERENCES public.firmas (id_firma) MATCH SIMPLE
              ON UPDATE NO ACTION
              ON DELETE NO ACTION,
          CONSTRAINT memorandum_comision_id_vehiculo_fkey FOREIGN KEY (id_vehiculo)
              REFERENCES public.vehiculos (id_vehiculo) MATCH SIMPLE
              ON UPDATE NO ACTION
              ON DELETE NO ACTION,
          CONSTRAINT memorandum_comision_tipo_transporte_check CHECK (tipo_transporte = ANY (ARRAY['publico'::text, 'oficial'::text, 'aereo'::text]))
      )
      TABLESPACE pg_default;
    `);

        // 3. Restaurar Permisos
        console.log('Restaurando permisos...');
        await client.query(`
      ALTER TABLE public.memorandum_comision OWNER to postgres;
      -- REVOKE ALL ON TABLE public.memorandum_comision FROM apps; -- (Opcional, create lo limpia)
      -- REVOKE ALL ON TABLE public.memorandum_comision FROM readers; 
      -- GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.memorandum_comision TO apps; -- (Si usas un usuario apps específico)
      -- GRANT ALL ON TABLE public.memorandum_comision TO postgres;
      -- GRANT SELECT ON TABLE public.memorandum_comision TO readers; 
    `);

        // 4. Restaurar Comentarios
        console.log('Restaurando comentarios...');
        await client.query(`
      COMMENT ON COLUMN public.memorandum_comision.id_memorandum_comision IS 'ID único';
      COMMENT ON COLUMN public.memorandum_comision.folio IS 'Folio personalizado por Área';
      COMMENT ON COLUMN public.memorandum_comision.id_actividad IS 'Actividad relacionada';
      COMMENT ON COLUMN public.memorandum_comision.id_empleado IS 'Empleado comisionado';
      COMMENT ON COLUMN public.memorandum_comision.periodo_inicio IS 'Fecha inicio del período';
      COMMENT ON COLUMN public.memorandum_comision.periodo_fin IS 'Fecha fin del período';
      COMMENT ON COLUMN public.memorandum_comision.tipo_transporte IS 'Tipo: publico, oficial, aereo';
      COMMENT ON COLUMN public.memorandum_comision.id_firma IS 'Firma del jefe de área';
      COMMENT ON COLUMN public.memorandum_comision.observaciones IS 'Observaciones adicionales del memorandum/comisión';
    `);

        await client.query('COMMIT');
        console.log('Tabla recreada exitosamente con folio en 2da posición.');

    } catch (error) {
        await client.query('ROLLBACK');
        console.error('Error recreando tabla:', error);
    } finally {
        client.release();
        pool.end();
    }
}

recreateSchema();
